<?php

// new different functions to the main object

namespace testingPatterns\DecoratorPattern;

interface ImplementComponent
{
    public function decorate(): string;
}

class InitComponent implements ImplementComponent
{
    public function decorate(): string
    {
        // TODO: Implement decorate() method.
        return 'INIT_PRODUCT';
    }
}

class InitDecorator implements ImplementComponent
{
    public ImplementComponent $implementComponent;

    public function __construct(ImplementComponent $implementComponent)
    {
        $this->implementComponent = $implementComponent;
    }

    public function decorate(): string
    {
        // TODO: Implement decorate() method.
        return $this->implementComponent->decorate();
    }
}

class Decorator1 extends InitDecorator
{
    public function decorate(): string
    {
        return 'DECORATOR_1(' . parent::decorate() . ')'; // TODO: Change the autogenerated stub
    }
}

class Decorator2 extends InitDecorator
{
    public function decorate(): string
    {
        return 'DECORATOR_2(' .  parent::decorate() . ')'; // TODO: Change the autogenerated stub
    }
}

function clientCode(ImplementComponent $component): void
{
    echo $component->decorate() . PHP_EOL;
}

$initComponent = new InitComponent();
clientCode($initComponent);

$decorator_1 = new Decorator1($initComponent);
$decorator_2 = new Decorator2($decorator_1);
clientCode($decorator_2);
