<?php

interface Component
{
    public function decorate(): string;
}

class ClassComponent implements Component
{
    public function decorate(): string
    {
        // TODO: Implement decorate() method.
        return 'initProduct';
    }
}

class ClassDecorator implements Component
{
    protected ?Component $component;
    public function __construct(Component $component)
    {
        $this->component = $component;
    }

    public function decorate(): string
    {
        // TODO: Implement decorate() method.
        return $this->component->decorate();
    }
}

class Decorator1 extends ClassDecorator
{
    public function decorate(): string
    {
        return __CLASS__ . '(' . parent::decorate() . ')'; // TODO: Change the autogenerated stub
    }
}


class Decorator2 extends ClassDecorator
{
    public function decorate(): string
    {
        return __CLASS__ . '(' . parent::decorate() . ')';
    }
}

function getDecoratorsResult(Component $component)
{
    echo 'RESULT:' . $component->decorate() . PHP_EOL;
}

$initProduct = new ClassComponent();
getDecoratorsResult($initProduct);

$productWithDecorator1 = new Decorator1($initProduct);
$productWithDecorator2 = new Decorator2($productWithDecorator1);
getDecoratorsResult($productWithDecorator2);
